[package]
name = "selendra-network-bridge"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
always-assert = "0.1"
async-trait = "0.1.57"
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
selendra-primitives = { path = "../../../../primitives" }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sc-network-common = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
selendra-node-subsystem = {path = "../../subsystem" }
selendra-overseer = { path = "../../overseer" }
selendra-node-network-protocol = { path = "../protocol" }
selendra-node-subsystem-util = { path = "../../subsystem-util"}
parking_lot = "0.12.0"
bytes = "1"
fatality = "0.0.6"
thiserror = "1"

[dev-dependencies]
assert_matches = "1.4.0"
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
futures-timer = "3"
selendra-primitives-test-helpers = { path = "../../../../primitives/test-helpers" }
