[package]
name = "selendra-network-bridge"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
bytes = "1"
fatality = "0.0.6"
thiserror = "1"
always-assert = "0.1"
async-trait = "0.1.53"
futures = "0.3.21"
parking_lot = "0.12.0"

parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }

selendra-primitives = { path = "../../../../primitives" }
selendra-node-subsystem = {path = "../../subsystem" }
selendra-overseer = { path = "../../overseer" }
selendra-node-network-protocol = { path = "../protocol" }
selendra-node-subsystem-util = { path = "../../subsystem-util"}
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
assert_matches = "1.4.0"
futures-timer = "3"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }

node-subsystem-test-helpers = { path = "../../../../tests/test-helpers/subsystem" }
primitives-test-helpers = { path = "../../../../tests/test-helpers/primitive" }
