[package]
name = "test-parachain-adder"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
description = "Test parachain which adds to a number as its state transition"
edition = "2021"
build = "build.rs"

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dlmalloc = { version = "0.2.4", features = [ "global" ] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
# We need to make sure the global allocator is disabled until we have support of full substrate externalities
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, features = [ "disable_allocator" ] , branch = "polkadot-v1.0.0" }

parachain = { package = "selendra-parachain", path = "../../", default-features = false, features = [ "wasm-api" ] }
[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

[features]
default = [ "std" ]
std = [
	"parachain/std",
	"sp-std/std",
]
