[package]
name = "selendra-node-core-runtime-api"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"


[dependencies]
futures = "0.3.21"
lru = "0.9"
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

gum = { package = "tracing-gum", path = "../../gum" }
selendra-primitives = { path = "../../../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-types = { path = "../../subsystem-types" }
selendra-node-metrics = { path = "../../metrics" }

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
selendra-node-primitives = { path = "../../primitives" }
test-helpers = { package = "selendra-primitives-test-helpers", path = "../../../../primitives/test-helpers" }
