[package]
name = "selendra"
version = "0.4.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
rust-version = "1.64.0" # custom profiles
description = "Implementation of a `https://selendra.network` node in Rust based on the Substrate framework."

[[bin]]
name = "selendra"
path = "src/main.rs"

[dependencies]
selendra-cli = { path = "../node/cli" }
color-eyre = { version = "0.6.1", default-features = false }
parity-util-mem = { version = "0.12.0", default-features = false, features = ["jemalloc-global"] }

[dev-dependencies]
assert_cmd = "2.0.4"
nix = "0.24.1"
tempfile = "3.2.0"
tokio = "1.22.0"
substrate-rpc-client = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
selendra-core-primitives = { path = "../primitives/core" }

[features]
runtime-benchmarks= [ "selendra-cli/runtime-benchmarks" ]
try-runtime = [ "selendra-cli/try-runtime" ]
fast-runtime = [ "selendra-cli/fast-runtime" ]
runtime-metrics = [ "selendra-cli/runtime-metrics" ]
pyroscope = ["selendra-cli/pyroscope"]

[badges]
maintenance = { status = "actively-developed" }