[package]
name = "selendra-primitives"
version = "3.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
license = "Apache 2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["max-encoded-len", "derive"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

serde = { workspace = true }
bstringify = { workspace = true }
hex-literal = { workspace = true }
num_enum = { workspace = true }
sp-api = { workspace = true }
sp-application-crypto = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-io = { workspace = true }
sp-std = { workspace = true }
sp-staking = { workspace = true }
frame-support = { workspace = true }
evm = { workspace = true }
evm-gasometer = { workspace = true }
evm-runtime = { workspace = true }
ethereum = { workspace = true }
pallet-evm-utility = { workspace = true }
pallet-evm-utility-macro = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "serde/std",
	"num_enum/std",
	"evm/std",
	"evm/with-serde",
	"evm-runtime/std",
	"evm-gasometer/std",
	"ethereum/with-serde",
    "sp-api/std",
	"sp-io/std",
    "sp-application-crypto/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
	"sp-staking/std",
	"pallet-evm-utility/std",

]
