[package]
name = "selendra-primitives"
version = "0.2.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
hex-literal = "0.3.4"
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.137", optional = true, features = ["derive"] }
scale-info = { version = "2.1.2", default-features = false, features = ["bit-vec", "derive"] }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["bit-vec", "derive"] }
parity-util-mem = { version = "0.11.0", default-features = false, optional = true }

frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-consensus-slots = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-keystore = { git = "https://github.com/paritytech/substrate", optional = true , branch = "polkadot-v0.9.26" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sp-trie = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }

selendra-core-primitives = { path = "core", default-features = false }
selendra-indracore = { path = "../indracore/core", default-features = false }

[features]
default = ["std"]
std = [
	"parity-util-mem",
	"bitvec/std",
	"serde/std",
	"scale-info/std",
	"parity-scale-codec/std",

	"frame-system/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-api/std",
	"sp-authority-discovery/std",
	"sp-consensus-slots/std",
	"sp-keystore",
	"sp-std/std",
	"sp-io/std",
	"sp-version/std",
	"sp-staking/std",
	"sp-arithmetic/std",
	"sp-runtime/std",
	"sp-trie/std",

    "selendra-core-primitives/std",
	"selendra-indracore/std"
]
