[package]
name = "selendra-primitives"
version = "0.2.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
selendra-core-primitives = { path = "core", default-features = false }

[features]
default = ["std"]
std = [
    "selendra-core-primitives/std",
]
