[package]
name = "selendra-node-core-approval-voting"
version = "0.2.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
lru = "0.7"
merlin = "2.0"
schnorrkel = "0.9.1"
kvdb = "0.11.0"
derive_more = "0.99.17"
thiserror = "1.0.31"
futures = "0.3.21"
futures-timer = "3.0.2"
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["bit-vec", "derive"] }

sc-keystore = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }
sp-consensus = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }
sp-consensus-slots = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false, features = ["full_crypto"] , branch = "polkadot-v0.9.29" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }

selendra-primitives = { path = "../../../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-overseer = { path = "../../overseer" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-jaeger = { path = "../../jaeger" }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
async-trait = "0.1.60"
parking_lot = "0.12.0"
rand_core = "0.5.1" # should match schnorrkel
assert_matches = "1.4.0"
kvdb-memorydb = "0.11.0"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }

node-subsystem-test-helpers = { path = "../../../../tests/test-helpers/subsystem" }
test-helpers = { package = "primitives-test-helpers", path = "../../../../tests/test-helpers/primitive" }
