[package]
name = "test-parachain-halt"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
description = "Test parachain which executes forever"
edition = "2021"
build = "build.rs"

[dependencies]

[build-dependencies]
rustversion = "1.0.6"
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

[features]
default = [ "std" ]
std = []
