[package]
name = "orchestra"
version = "0.0.1"
authors = ["Selendra <info@selendra.org>"]
description = "Generate an orchestra of subsystems from a single struct."
license = "MIT OR Apache-2.0"
edition = "2021"

autoexamples = false

[dependencies]
tracing = "0.1.35"
futures = "0.3"
async-trait = "0.1.60"
thiserror = "1"
futures-timer = "3.0.2"
pin-project = "1.0"
dyn-clonable = "0.9"

orchestra-proc-macro = { version = "0.0.1", path = "./proc-macro" }
metered = { package = "prioritized-metered-channel", version = "0.2.0", path = "../metered-channel" }

[dev-dependencies]
trybuild = "1.0.61"
rustversion = "1.0.6"

[[example]]
name = "duo"
crate-type = ["bin"]

[[example]]
name = "solo"
crate-type = ["bin"]

[features]
default = []
expand = ["orchestra-proc-macro/expand"]
