[workspace]

members = [
    "node",
    "runtime",
    "consensus/aggregator",
    "consensus/clique",
    "consensus/finality-selendra",
    "pallets/selendra",
    "pallets/elections",
    "pallets/support",
    "pallets/committee-management",
    "primitives",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
