[workspace]
members = [
    "primitives",
    "node/cli",
    "node/inspect",
    "node/rpc",
    "node/executor",
    "node/test",
    "runtime/selendra",
	"modules/support",
	"modules/idle-scheduler",
	"modules/evm-accounts",
	"modules/transaction-payment",
	"modules/dex",
	"modules/currencies"
]

[profile.release]
panic = "unwind"
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
