cargo-features = ["resolver"]

[workspace]
members = [
	"primitives",
	"runtime/common",
	"runtime/selendra/constants",
	# "rpc",
	# "node/service",
	# "node/cli",
	# "node",
	# "modules/*",
	# "inspect",
	# "utils/generate-bags"
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
