[workspace]
members = [
    "primitives",
    "node/cli",
    "node/inspect",
    "node/rpc",
    "node/executor",
    "node/test",
    "runtime/selendra",
]

[profile.release]
panic = "unwind"
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
