cargo-features = ["resolver"]

[workspace]
members = [
	"primitives",
	"indracore/core",
	"indracore/metrics",
	"runtime/common",
	"runtime/common/slot_range_helper",
	"runtime/selendra",
	"runtime/selendra/constants",
	"rpc",
	"node/service",
	"node/cli",
	"node",
	"inspect",
	# "utils/generate-bags"
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
