cargo-features = ["resolver"]

[workspace]
members = [
	"primitives",
	"indracore/core",
	"indracore/metrics",
	"indracore/runtime",
	"indracore/xcm",
	"indracore/xcm/pallet-xcm",
	"indracore/xcm/pallet-xcm/benchmarks",
	"indracore/xcm/xcm-builder",
	"indracore/xcm/xcm-executor",
	"runtime/common",
	"runtime/common/slot_range_helper",
	"runtime/selendra",
	"runtime/selendra/constants",
	"node/node-helper/primitives",
	"node/node-helper/statement-table",
	"node/node-helper/erasure-coding",
	"node/node-helper/jaeger",
	"node/node-helper/gum",
	"node/node-helper/metered-channel",
	"node/node-helper/metrics",
	"node/node-helper/network/protocol",
	"rpc",
	"node/service",
	"node/cli",
	"node",
	"inspect",
	# "utils/generate-bags"
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
