[package]
name = "selendra-node-jaeger"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
description = "Selendra Jaeger primitives, but equally useful for Grafana/Tempo"
edition = "2021"

[dependencies]
async-std = "1.11.0"
mick-jaeger = "0.1.8"
lazy_static = "1.4"
parking_lot = "0.12.0"
thiserror = "1.0.31"
log = "0.4.17"
parity-scale-codec = { version = "3.1.5", default-features = false }

sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }

selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../primitives" }
