[package]
name = "selendra-node-jaeger"
version = "0.4.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Selendra Jaeger primitives, but equally useful for Grafana/Tempo"

[dependencies]
tokio = "1.22.0"
mick-jaeger = "0.1.8"
lazy_static = "1.4"
parking_lot = "0.12.0"
selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../primitives" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
thiserror = "1.0.31"
log = "0.4.17"
parity-scale-codec = { version = "3.1.5", default-features = false }
