[package]
name = "selendra-runtime-metrics"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
bs58 = { version = "0.4.0", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "3.6.1", default-features = false }

sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false, optional = true }


primitives = { package = "selendra-primitives", path = "../../primitives", default-features = false }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"sp-tracing/std",
    "parity-scale-codec/std",
    "primitives/std",
    "bs58/std"
]
runtime-metrics = ["sp-tracing/with-tracing", "frame-benchmarking"]
