[package]
name = "selendra-parachain"
version = "0.2.2"
authors = ["Selendra <info@selendra.org>"]
description = "Core types and utilities for creating and working with parachain"
edition = "2021"

[dependencies]
derive_more = "0.99.11"
serde = { version = "1.0.140", default-features = false, features = [ "derive" ], optional = true }
parity-scale-codec = { version = "3.1.5", default-features = false, features = [ "derive" ] }
parity-util-mem = { version = "0.11.0", default-features = false, optional = true }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }

sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.28" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.28" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.28" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.28" }

selendra-core-primitives = { path = "../../primitives/core", default-features = false }

[features]
default = ["std"]
wasm-api = []
std = [
	"serde/std",
	"scale-info/std",
	"parity-scale-codec/std",
	"parity-util-mem",

	"sp-std/std",
	"sp-runtime/std",
	"sp-core/std",
	"frame-support/std",

	"selendra-core-primitives/std",
]
runtime-benchmarks = []
