[package]
name = "forests-client-consensus-relay-chain"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
description = "The relay-chain provided consensus algorithm"
edition = "2021"

[dependencies]
async-trait = "0.1.60"
futures = "0.3.21"
parking_lot = "0.12.1"
tracing = "0.1.35"

# Substrate
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }

# Forests
forests-client-consensus-common = { path = "../common" }
forests-primitives-core = { path = "../../../primitives/core" }
forests-relay-chain-interface = { path = "../../relay-chain-interface" }
