[package]
name = "selendra-service"
version = "0.2.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
# External Crates
futures = "0.3.21"
hex-literal = "0.3.4"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
kvdb = "0.11.0"
kvdb-rocksdb = { version = "0.15.2", optional = true }
parity-db = { version = "0.3.13", optional = true }
async-trait = "0.1.53"
lru = "0.7"

# Substrate Client
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-sysinfo = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-service = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.26" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
beefy-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
beefy-gadget = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }

# Substrate Primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }

# Substrate Pallets
pallet-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }

# Substrate Other
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }

# Selendra
selendra-primitives = { path = "../../primitives" }
selendra-indracore = { path = "../../indracore/core" }
selendra-runtime-indracores = { path = "../../indracore/runtime" }
selendra-rpc = { path = "../rpc" }
selendra-client = { path = "../client", default-features = false, optional = true }
selendra-node-primitives = { path = "../node-helper/primitives" }
selendra-node-core-indracores-inherent = { path = "../node-helper/core/indracores-inherent" }
selendra-overseer = { path = "../node-helper/overseer" }
selendra-node-subsystem = {path = "../node-helper/subsystem" }
selendra-node-subsystem-util = { path = "../node-helper/subsystem-util" }
selendra-node-subsystem-types = { path = "../node-helper/subsystem-types" }
selendra-node-network-protocol = { path = "../node-helper/network/protocol" }
gum = { package = "tracing-gum", path = "../node-helper/gum" }

# Selendra Runtimes
selendra-runtime = { path = "../../runtime/selendra", optional = true }
selendra-runtime-constants = { path = "../../runtime/selendra/constants", optional = true }

# Selendra Subsystems
selendra-approval-distribution = { path = "../node-helper/network/approval-distribution", optional = true }
selendra-availability-bitfield-distribution = { path = "../node-helper/network/bitfield-distribution", optional = true }
selendra-availability-distribution = { path = "../node-helper/network/availability-distribution", optional = true }
selendra-availability-recovery = { path = "../node-helper/network/availability-recovery", optional = true }
selendra-collator-protocol = { path = "../node-helper/network/collator-protocol", optional = true }
selendra-dispute-distribution = { path = "../node-helper/network/dispute-distribution", optional = true }
selendra-gossip-support = { path = "../node-helper/network/gossip-support", optional = true }
selendra-network-bridge = { path = "../node-helper/network/bridge", optional = true }
selendra-statement-distribution = { path = "../node-helper/network/statement-distribution", optional = true }
selendra-node-collation-generation = { path = "../node-helper/collation-generation", optional = true }
selendra-node-core-approval-voting = { path = "../node-helper/core/approval-voting", optional = true }
selendra-node-core-av-store = { path = "../node-helper/core/av-store", optional = true }
selendra-node-core-backing = { path = "../node-helper/core/backing", optional = true }
selendra-node-core-bitfield-signing = { path = "../node-helper/core/bitfield-signing", optional = true }
selendra-node-core-candidate-validation = { path = "../node-helper/core/candidate-validation", optional = true }
selendra-node-core-chain-api = { path = "../node-helper/core/chain-api", optional = true }
selendra-node-core-chain-selection = { path = "../node-helper/core/chain-selection", optional = true }
selendra-node-core-dispute-coordinator = { path = "../node-helper/core/dispute-coordinator", optional = true }
selendra-node-core-provisioner = { path = "../node-helper/core/provisioner", optional = true }
selendra-node-core-pvf-checker = { path = "../node-helper/core/pvf-checker", optional = true }
selendra-node-core-runtime-api = { path = "../node-helper/core/runtime-api", optional = true }

[dev-dependencies]
env_logger = "0.9.0"
log = "0.4.17"
assert_matches = "1.5.0"
test-client = { path = "../../tests/test-helpers/client" }
node-subsystem-test-helpers = { path = "../../tests/test-helpers/subsystem" }

[features]
default = ["db", "full-node", "selendra-native"]

db = [
	"sc-service/rocksdb"
]

full-node = [
	"selendra-node-core-av-store",
	"selendra-node-core-approval-voting",
	"selendra-availability-bitfield-distribution",
	"selendra-availability-distribution",
	"selendra-availability-recovery",
	"selendra-client",
	"selendra-collator-protocol",
	"selendra-dispute-distribution",
	"selendra-gossip-support",
	"selendra-network-bridge",
	"selendra-node-collation-generation",
	"selendra-node-core-backing",
	"selendra-node-core-bitfield-signing",
	"selendra-node-core-candidate-validation",
	"selendra-node-core-chain-api",
	"selendra-node-core-chain-selection",
	"selendra-node-core-dispute-coordinator",
	"selendra-node-core-provisioner",
	"selendra-node-core-runtime-api",
	"selendra-statement-distribution",
	"selendra-approval-distribution",
	"selendra-node-core-pvf-checker",
	"kvdb-rocksdb",
	"parity-db",
]

# Configure the native runtimes to use. Selendra is enabled by default.
#
# Validators require the native runtime currently
selendra-native = [ "selendra-runtime", "selendra-runtime-constants", "selendra-client/selendra" ]

runtime-benchmarks = [
	"selendra-runtime/runtime-benchmarks",
]
try-runtime = [
	"selendra-runtime/try-runtime",
]
fast-runtime = [
	"selendra-runtime/fast-runtime",
]

malus = ["full-node"]

runtime-metrics = [
	"selendra-client/runtime-metrics",
	"selendra-runtime/runtime-metrics",
	"selendra-runtime-indracores/runtime-metrics"
]

staging-client = ["selendra-node-core-provisioner/staging-client"]
