[package]
name = "selendra-node-core-av-store"
version = "0.4.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
kvdb = "0.12.0"
thiserror = "1.0.31"
bitvec = "1.0.0"
parity-scale-codec = { version = "3.1.5", features = ["derive"] }
gum = { package = "tracing-gum", path = "../../gum" }
erasure = { package = "selendra-erasure-coding", path = "../../erasure-coding" }
selendra-node-subsystem = {path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-overseer = { path = "../../overseer" }
selendra-primitives = { path = "../../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }

[dev-dependencies]
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"
kvdb-memorydb = "0.12.0"
parking_lot = "0.12.0"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "selendra-primitives-test-helpers", path = "../../../../primitives/test-helpers" }
