[package]
name = "selendra-rpc"
version = "3.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = ["derive"] }
jsonrpsee = { workspace = true, features = ["server"] }

log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
libp2p = { workspace = true }
thiserror = { workspace = true }

sp-blockchain = { workspace = true }
sp-runtime = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sc-client-api = { workspace = true }
sc-rpc = { workspace = true }
sc-rpc-api = { workspace = true }
sc-transaction-pool-api = { workspace = true }
pallet-transaction-payment-rpc = { workspace = true }
substrate-frame-rpc-system = { workspace = true }
selendra-primitives = { workspace = true }
finality-selendra = { workspace = true }
