[package]
name = "selendra-gossip-support"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

selendra-node-network-protocol = { path = "../protocol" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-primitives = { path = "../../../../primitives" }

futures = "0.3.21"
futures-timer = "3.0.2"
rand = { version = "0.8.5", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
async-trait = "0.1.57"
lazy_static = "1.4.0"
