[package]
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
name = "xcm-executor-integration-tests"
description = "Integration tests for the XCM Executor"
version = "0.2.7"

[dependencies]
futures = "0.3.21"

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }

pallet-xcm = { path = "../../pallet-xcm" }
selendra-test-client = { path = "../../../../node/test/client" }
selendra-test-runtime = { path = "../../../../runtime/test-runtime" }
selendra-test-service = { path = "../../../../node/test/service" }
xcm = { path = "../..", default-features = false }
xcm-executor = { path = ".." }

[features]
default = ["std"]
std = [
	"xcm/std",
	"sp-runtime/std",
	"frame-support/std",
]
