[package]
name = "test-indracore-halt"
version = "0.2.0"
authors = ["Selendra <info@selendra.org>"]
description = "Test indracore which executes forever"
edition = "2021"
build = "build.rs"

[dependencies]

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }

[features]
default = [ "std" ]
std = []
