[package]
name = "selendra-node-collation-generation"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
thiserror = "1.0.31"
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["bit-vec", "derive"] }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-maybe-compressed-blob  = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }

selendra-erasure-coding = { path = "../erasure-coding" }
selendra-node-primitives = { path = "../primitives" }
selendra-node-subsystem = { path = "../subsystem" }
selendra-node-subsystem-util = { path = "../subsystem-util" }
selendra-primitives = { path = "../../../primitives" }
gum = { package = "tracing-gum", path = "../gum" }

[dev-dependencies]
node-subsystem-test-helpers = { path = "../../../tests/test-helpers/subsystem" }
test-helpers = { package = "primitives-test-helpers", path = "../../../tests/test-helpers/primitive" }
