[package]
name = "erasure_coding_fuzzer"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
honggfuzz = "0.5"

selendra-erasure-coding = { path = ".." }
selendra-primitives = { path = "../../../../primitives" }
primitives = { package = "selendra-node-primitives", path = "../primitives" }

[[bin]]
name = "reconstruct"
path = "src/reconstruct.rs"

[[bin]]
name = "round_trip"
path = "src/round_trip.rs"
