[package]
name = "selendra-runtime-common"
version = "3.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

serde = { workspace = true }
sp-api = { workspace = true }
sp-application-crypto = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }
sp-staking = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-balances = { workspace = true }
pallet-authorship = { workspace = true }
pallet-transaction-payment = { workspace = true }

selendra-primitives = { workspace = true }

[features]
default = [ "std" ]
std = [
	"codec/std",
    "serde/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-staking/std",
	"frame-system/std",
	"frame-support/std",
	"pallet-balances/std",
	"pallet-authorship/std",
	"pallet-transaction-payment/std",
    "selendra-primitives/std"
]
