
[package]
name = "tracing-gum"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
description = "Stick logs together with the TraceID as provided by tempo"
edition = "2021"

[dependencies]
tracing = "0.1.34"
jaeger = { path = "../jaeger", package = "selendra-node-jaeger" }
gum-proc-macro = { path = "./proc-macro", package = "tracing-gum-proc-macro" }
selendra-primitives = { path = "../../../primitives", features = ["std"] }
