[package]
name = "tracing-gum"
version = "0.4.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Stick logs together with the TraceID as provided by tempo"

[dependencies]
tracing = "0.1.35"
jaeger = { path = "../jaeger", package = "selendra-node-jaeger" }
gum-proc-macro = { path = "./proc-macro", package = "tracing-gum-proc-macro" }
selendra-primitives = { path = "../../../primitives", features = ["std"] }
