[package]
name = "selendra-node-primitives"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Primitives types for the Node-side"

[dependencies]
bounded-vec = "0.7"
futures = "0.3.21"
schnorrkel = "0.9.1"
thiserror = "1.0.31"
serde = { version = "1.0.163", features = ["derive"] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-maybe-compressed-blob = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

selendra-primitives = { path = "../../../primitives" }
selendra-parachain = { path = "../../../parachain", default-features = false }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = { version = "0.11.2", default-features = false }

[dev-dependencies]
selendra-erasure-coding = { path = "../erasure-coding" }
