
[package]
name = "selendra-node-primitives"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
description = "Primitives types for the Node-helper-side"
edition = "2021"

[dependencies]
bounded-vec = "0.6"
futures = "0.3.21"
schnorrkel = "0.9.1"
thiserror = "1.0.31"
serde = { version = "1.0.140", features = ["derive"] }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-consensus-vrf = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-maybe-compressed-blob = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }

selendra-parachain = { path = "../../../parachain/core", default-features = false }
selendra-primitives = { path = "../../../primitives" }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = { version = "0.11.2", default-features = false }

[dev-dependencies]
selendra-erasure-coding = { path = "../erasure-coding" }
