[package]
name = "forests-client-network"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
description = "Forests-specific networking protocol"
edition = "2021"

[dependencies]
async-trait = "0.1.60"
codec = { package = "parity-scale-codec", version = "3.1.5", features = [ "derive" ] }
derive_more = "0.99.2"
futures = "0.3.21"
futures-timer = "3.0.2"
parking_lot = "0.12.1"
tracing = "0.1.35"

# Substrate
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }

# Selendra
selendra-node-primitives = { path = "../../../node/node-helper/primitives" }
selendra-parachain = { path = "../../../parachain/core" }
selendra-primitives = { path = "../../../primitives" }

# Forests
forests-relay-chain-interface = { path = "../relay-chain-interface" }

[dev-dependencies]
portpicker = "0.1.1"
tokio = { version = "1.19.2", features = ["macros"] }
url = "2.2.2"

# Substrate
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
substrate-test-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }

# Selendra
selendra-client = { path = "../../../node/client" }
selendra-service = { path = "../../../node/service" }
test-client = { path = "../../../tests/test-helpers/client" }

# Forests
forests-primitives-core = { path = "../../primitives/core" }
forests-relay-chain-inprocess-interface = { path = "../relay-chain-inprocess-interface" }
forests-test-service = { path = "../../../tests/test-helpers/forests/service" }
