[package]
name = "pallet-evm-utility-macro"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
pallet-evm-utility = { workspace = true }

[lib]
proc-macro = true
