[package]
name = "selendra-node-core-pvf-checker"
version = "0.2.5"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
thiserror = "1.0.37"
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }

gum = { package = "tracing-gum", path = "../../gum" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-primitives = { path = "../../../../primitives" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-overseer = { path = "../../overseer" }

[dev-dependencies]
futures-timer = "3.0.2"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }

node-subsystem-test-helpers = { path = "../../../../tests/test-helpers/subsystem"}
test-helpers = { package = "primitives-test-helpers", path = "../../../../tests/test-helpers/primitive" }
