[package]
name = "xcm-simulator"
version = "0.2.7"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Test kit to simulate cross-chain message passing and XCM execution"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
paste = "1.0.7"

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }

xcm = { path = "../" }
xcm-executor = { path = "../xcm-executor" }
selendra-core-primitives = { path = "../../../primitives/core"}
selendra-parachain = { path = "../.." }
selendra-runtime-parachains = { path = "../../runtime" }
