[package]
name = "selendra-erasure-coding"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
thiserror = "1.0.31"
novelpoly = { package = "reed-solomon-novelpoly", version = "1.0.0" }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["std", "derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { package = "selendra-node-primitives", path = "../primitives" }

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name = "scaling_with_validators"
harness = false
