[package]
name = "selendra-erasure-coding"
version = "0.3.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { package = "selendra-node-primitives", path = "../primitives" }
novelpoly = { package = "reed-solomon-novelpoly", version = "1.0.0" }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["std", "derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
thiserror = "1.0.31"
