[package]
name = "selendra-node-subsystem-util"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Subsystem traits and message definitions"

[dependencies]
async-trait = "0.1.57"
futures = "0.3.21"
futures-channel = "0.3.23"
itertools = "0.10"
parking_lot = "0.11.2"
pin-project = "1.0.9"
rand = "0.8.5"
thiserror = "1.0.31"
fatality = "0.0.6"
gum = { package = "tracing-gum", path = "../gum" }
derive_more = "0.99.17"
lru = "0.9.0"
kvdb = "0.13.0"
parity-db = { version = "0.4.8"}
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }

selendra-node-subsystem = {path = "../subsystem" }
selendra-node-jaeger = { path = "../jaeger" }
selendra-node-metrics = { path = "../metrics" }
selendra-node-network-protocol = { path = "../network/protocol" }
selendra-primitives = { path = "../../../primitives" }
selendra-node-primitives = { path = "../primitives" }
selendra-overseer = { path = "../overseer" }
metered = { package = "prioritized-metered-channel", version = "0.2.0" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }


[dev-dependencies]
assert_matches = "1.4.0"
env_logger = "0.9.0"
futures = { version = "0.3.21", features = ["thread-pool"] }
log = "0.4.17"
lazy_static = "1.4.0"
kvdb-shared-tests = "0.11.0"
tempfile = "3.1.0"
kvdb-memorydb = "0.13.0"

selendra-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
selendra-primitives-test-helpers = { path = "../../../primitives/test-helpers" }