[package]
name = "selendra-node-subsystem-util"
version = "0.2.5"
authors = ["Selendra <info@selendra.org>"]
description = "Subsystem traits and message definitions"
edition = "2021"

[dependencies]
async-trait = "0.1.60"
futures = "0.3.21"
itertools = "0.10"
parking_lot = "0.12.1"
pin-project = "1.0.9"
rand = "0.8.5"
thiserror = "1.0.37"
fatality = "0.0.6"
derive_more = "0.99.17"
lru = "0.8.0"
kvdb = "0.12.0"
parity-db = { version = "0.3.16" }
parity-util-mem = { version = "0.12.0", default-features = false }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
metered = { package = "prioritized-metered-channel", version = "0.2.0" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }

selendra-primitives = { path = "../../../primitives" }
selendra-node-subsystem = {path = "../subsystem" }
selendra-node-jaeger = { path = "../jaeger" }
selendra-node-metrics = { path = "../metrics" }
selendra-node-network-protocol = { path = "../network/protocol" }
selendra-node-primitives = { path = "../primitives" }
selendra-overseer = { path = "../overseer" }
gum = { package = "tracing-gum", path = "../gum" }

[dev-dependencies]
assert_matches = "1.4.0"
env_logger = "0.9.0"
futures = { version = "0.3.21", features = ["thread-pool"] }
log = "0.4.17"
lazy_static = "1.4.0"
kvdb-shared-tests = "0.10.0"
tempfile = "3.1.0"

primitives-test-helpers = { path = "../../../tests/test-helpers/primitive" }
node-subsystem-test-helpers = { path = "../../../tests/test-helpers/subsystem" }
