[package]
name = "selendra-node-core-chain-selection"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Chain Selection Subsystem"

[dependencies]
futures = "0.3.21"
futures-timer = "3"
kvdb = "0.12.0"
thiserror = "1.0.31"
parity-scale-codec = "3.1.5"
gum = { package = "tracing-gum", path = "../../gum" }
selendra-primitives = { path = "../../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
parking_lot = "0.12.0"
assert_matches = "1"
kvdb-memorydb = "0.12.0"
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
