[package]
name = "selendra-node-metrics"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
description = "Subsystem metric helpers"
edition = "2021"


[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
log = "0.4.17"
bs58 = { version = "0.4.0", features = ["alloc"] }
gum = { package = "tracing-gum", path = "../gum" }
codec = { package = "parity-scale-codec", version = "3.0.0" }

sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }

primitives = { package = "selendra-primitives", path = "../../../primitives/" }
metered = { package = "prioritized-metered-channel", path = "../metered-channel" }

[dev-dependencies]
assert_cmd = "2.0.4"
nix = "0.24.1"
tempfile = "3.2.0"
tokio = "1.19.2"
prometheus-parse = {version = "0.2.2"}
hyper = { version = "0.14.20", default-features = false, features = ["http1", "tcp"] }
substrate-test-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
test-service = { path = "../../../tests/test-helpers/service", features=["runtime-metrics"]}

[features]
default = []
runtime-metrics = []
runtime-benchmarks = []
