[package]
name = "selendra-node-metrics"
version = "0.4.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Subsystem metric helpers"

[dependencies]
bs58 = { version = "0.4.0", features = ["alloc"] }
log = "0.4.17"
futures = "0.3.21"
futures-timer = "3.0.2"
metered = { package = "prioritized-metered-channel", version = "0.2.0" }
codec = { package = "parity-scale-codec", version = "3.0.0" }

# Both `sc-service` and `sc-cli` are required by runtime metrics `logger_hook()`.
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }

gum = { package = "tracing-gum", path = "../gum" }
primitives = { package = "selendra-primitives", path = "../../../primitives/" }

[dev-dependencies]
hyper = { version = "0.14.20", default-features = false, features = ["http1", "tcp"] }
prometheus-parse = {version = "0.2.2"}
assert_cmd = "2.0.4"
nix = "0.24.1"
tempfile = "3.2.0"
tokio = "1.22.0"
substrate-test-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }

selendra-test-service = { path = "../../test/service", features=["runtime-metrics"]}

[features]
default = []
runtime-metrics = []
runtime-benchmarks = []
