[package]
name = "selendra-node-core-dispute-coordinator"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
parity-scale-codec = "3.6.1"
kvdb = "0.13.0"
thiserror = "1.0.31"
lru = "0.9.0"
fatality = "0.0.6"
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

gum = { package = "tracing-gum", path = "../../gum" }
selendra-primitives = { path = "../../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
futures-timer = "3.0.2"
assert_matches = "1.4.0"
kvdb-memorydb = "0.13.0"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "selendra-primitives-test-helpers", path = "../../../../primitives/test-helpers" }

[features]
# If not enabled, the dispute coordinator will do nothing.
disputes = []
