[package]
name = "selendra-node-core-dispute-coordinator"
version = "0.2.5"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
kvdb = "0.12.0"
thiserror = "1.0.37"
lru = "0.8.0"
fatality = "0.0.6"
parity-scale-codec = "3.1.5"
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }

selendra-primitives = { path = "../../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
kvdb-memorydb = "0.12.0"
assert_matches = "1.4.0"
futures-timer = "3.0.2"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }

test-helpers = { package = "primitives-test-helpers", path = "../../../../tests/test-helpers/primitive" }
node-subsystem-test-helpers = { path = "../../../../tests/test-helpers/subsystem" }

[features]
# If not enabled, the dispute coordinator will do nothing.
disputes = []
