[package]
name = "selendra-test-malus"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
description = "Misbehaving nodes for local testnets, system and Simnet tests."
edition = "2021"

[[bin]]
name = "malus"
path = "src/malus.rs"

[dependencies]
assert_matches = "1.5"
async-trait = "0.1.53"
clap = { version = "3.1", features = ["derive"] }
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../gum/" }
erasure = { package = "selendra-erasure-coding", path = "../../erasure-coding" }
parity-util-mem = { version = "0.11.0", default-features = false, features = ["jemalloc-global"] }
color-eyre = { version = "0.6.1", default-features = false }

sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }

selendra-cli = { path = "../../cli", features = [ "malus", "selendra-native" ] }
selendra-node-subsystem = { path = "../subsystem" }
selendra-node-subsystem-util = { path = "../subsystem-util" }
selendra-node-subsystem-types = { path = "../subsystem-types" }
selendra-node-core-dispute-coordinator = { path = "../core/dispute-coordinator" }
selendra-node-core-candidate-validation = { path = "../core/candidate-validation" }
selendra-node-core-backing = { path = "../core/backing" }
selendra-node-primitives = { path = "../primitives" }
selendra-primitives = { path = "../../../primitives" }
selendra-node-core-pvf = { path = "../core/pvf" }

[features]
default = []

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
node-subsystem-test-helpers = { path = "../../../tests/test-helpers/subsystem" }


