[package]
name = "xcm-procedural"
version = "0.2.7"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.43"
quote = "1.0.20"
syn = "1.0.95"
Inflector = "0.11.4"
