[package]
name = "xcm-procedural"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.28"
syn = "2.0.15"
Inflector = "0.11.4"
