[package]
name = "selendra"
version = "3.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
build = "build.rs"
license = "GPL-3.0-or-later"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "selendra"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = ["derive"] }

log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
libp2p = { workspace = true }
thiserror = { workspace = true }

sp-api = { workspace = true }
sp-core = { workspace = true }
sp-blockchain = { workspace = true }
sp-application-crypto = { workspace = true }
sp-keystore = { workspace = true }
sp-inherents = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-consensus = { workspace = true }
sp-runtime = { workspace = true }
sp-timestamp = { workspace = true }
sp-arithmetic = { workspace = true }
sp-io = { workspace = true }

sc-block-builder = { workspace = true }
sc-consensus = { workspace = true }
sc-chain-spec = { workspace = true }
sc-cli = { workspace = true }
sc-executor = { workspace = true }
sc-service = { workspace = true }
sc-telemetry = { workspace = true }
sc-keystore = { workspace = true }
sc-basic-authorship = { workspace = true }
sc-network = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sc-consensus-aura = { workspace = true }
sc-client-api = { workspace = true }
sc-consensus-slots = { workspace = true }

frame-benchmarking-cli = { workspace = true, optional = true }
frame-benchmarking = { workspace = true, optional = true }
pallet-staking = { workspace = true }
try-runtime-cli = { workspace = true, optional = true }

selendra-primitives = { workspace = true }
selendra-runtime = { workspace = true }
selendra-runtime-common = { workspace = true }
finality-selendra = { workspace = true }
selendra-rpc = { workspace = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[features]
default = []
try-runtime = [
    "selendra-runtime/try-runtime",
    "try-runtime-cli/try-runtime",
]
only_legacy = [
    "finality-selendra/only_legacy"
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-benchmarking-cli/runtime-benchmarks",
    "selendra-runtime/runtime-benchmarks",
]
