[package]
name = "pallets-support"
version = "0.1.1"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38" }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "sp-std/std"
]
try-runtime = [
    "frame-support/try-runtime",
]
