[package]
name = "pallets-support"
version = "0.1.1"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
impl-trait-for-tuples = { workspace = true }
frame-support = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
selendra-primitives = { workspace = true }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"selendra-primitives/std"
]
try-runtime = [
    "frame-support/try-runtime",
]
