[package]
name = "selendra-node-network-protocol"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Primitives types for the Node-side"

[dependencies]
async-channel = "1.8.0"
async-trait = "0.1.57"
hex = "0.4.3"
strum = { version = "0.24", features = ["derive"] }
futures = "0.3.21"
thiserror = "1.0.31"
fatality = "0.0.6"
rand = "0.8"
derive_more = "0.99"
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

selendra-primitives = { path = "../../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-jaeger = { path = "../../jaeger" }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
rand_chacha = "0.3.1"
