[package]
name = "pallet-evm"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.2.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.145", optional = true, features = ["derive"], default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"], optional = true }
hex = { version = "0.4", default-features = false, features = ["alloc"], optional = true }

ripemd160 = { workspace = true }
rlp = { workspace = true }
tiny-keccak = { workspace = true }
sha3 = { workspace = true }
hex-literal = { workspace = true }
num = { workspace = true }
bn = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-balances = { workspace = true }
pallet-transaction-payment = { workspace = true }

pallets-support = { workspace = true }
pallet-evm-utility = { workspace = true }
pallet-idle-scheduler = { workspace = true }
selendra-primitives = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
env_logger = { workspace = true }
serde_json = { workspace = true }
pallet-utility = { workspace = true }

[features]
default = ["std"]
std = [
	"serde",
	"num/std",
	"rlp/std",
	"sha3/std",
	"ripemd160/std",
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-evm-utility/std",
	"pallets-support/std",
	"pallet-balances/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-idle-scheduler/std",
	"selendra-primitives/std",

]
with-ethereum-compatibility = []
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-timestamp/try-runtime",
]
tracing = ["pallet-evm-utility/tracing"]
bench = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"hex",
	"serde_json",
	"sp-runtime/runtime-benchmarks",
]
