[package]
name = "selendra-node-core-chain-api"
version = "0.3.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

gum = { package = "tracing-gum", path = "../../gum" }
selendra-primitives = { path = "../../../../primitives" }
selendra-node-subsystem = {path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
maplit = "1.0.2"
parity-scale-codec = "3.1.5"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

