[package]
name = "selendra-overseer"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
parking_lot = "0.12.0"
orchestra = "0.0.5"
lru = "0.9"
async-trait = "0.1.57"
tikv-jemalloc-ctl = { version = "0.5.0", optional = true }

client = { package = "sc-client-api", git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

selendra-node-network-protocol = { path = "../network/protocol" }
selendra-node-primitives = { path = "../primitives" }
selendra-node-subsystem-types = { path = "../subsystem-types" }
selendra-node-metrics = { path = "../metrics" }
selendra-primitives = { path = "../../../primitives" }
gum = { package = "tracing-gum", path = "../gum" }

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
femme = "2.2.1"
assert_matches = "1.4.0"
metered = { package = "prioritized-metered-channel", version = "0.2.0" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

test-helpers = { package = "selendra-primitives-test-helpers", path = "../../../primitives/test-helpers" }

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemalloc-ctl = "0.5.0"

[features]
default = []
expand = ["orchestra/expand"]
dotgraph = ["orchestra/dotgraph"]
jemalloc-allocator = ["dep:tikv-jemalloc-ctl"]