[package]
name = "selendra-cli"
version = "0.3.0"
authors = ["Selendra <info@selendra.org>"]
description = "Selendra Relay-chain Client Node"
edition = "2021"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on Linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "4.0.9", features = ["derive"], optional = true }
log = "0.4.17"
thiserror = "1.0.31"
futures = "0.3.21"
pyro = { package = "pyroscope", version = "0.3.1", optional = true }

service = { package = "selendra-service", path = "../service", default-features = false, optional = true }
selendra-client = { path = "../client", optional = true }
selendra-node-core-pvf = { path = "../node-helper/core/pvf", optional = true }
selendra-performance-test = { path = "../test/performance-test", optional = true }
selendra-node-metrics = { path = "../node-helper/metrics" }


frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34", optional = true }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34", optional = true }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sc-sysinfo = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34", optional = true }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34", optional = true }

# this crate is used only to enable `trie-memory-tracker` feature
# see https://github.com/paritytech/substrate/pull/6745
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34", default-features = false }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }

[features]
default = ["db", "cli", "hostperfcheck", "full-node", "trie-memory-tracker", "selendra-native"]
db = ["service/db"]
cli = [
	"clap",
	"sc-cli",
	"sc-service",
	"sc-tracing",
	"frame-benchmarking-cli",
	"try-runtime-cli",
	"selendra-client",
	"selendra-node-core-pvf",
]
runtime-benchmarks = [
	"service/runtime-benchmarks",
	"selendra-node-metrics/runtime-benchmarks",
	"selendra-performance-test?/runtime-benchmarks"
]
trie-memory-tracker = ["sp-trie/memory-tracker"]
full-node = ["service/full-node"]
try-runtime = ["service/try-runtime", "try-runtime-cli/try-runtime"]
fast-runtime = ["service/fast-runtime"]
pyroscope = ["pyro"]
hostperfcheck = ["selendra-performance-test"]

# Configure the native runtimes to use. Selendra is enabled by default.
#
# Validators require the native runtime currently
selendra-native = ["service/selendra-native"]

malus = ["full-node", "service/malus"]
runtime-metrics = ["service/runtime-metrics", "selendra-node-metrics/runtime-metrics"]
