[package]
name = "selendra-voter-bags"
version = "0.2.2"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }

generate-bags = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28" }
selendra-runtime = { path = "../../runtime/selendra" }
