[package]
name = "selendra-node-executor"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
scale-info = { version = "2.1.1", features = ["derive"] }

frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sc-executor = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-keystore = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-state-machine = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-tracing = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-trie = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }

selendra-primitives = { path = "../../primitives" }
selendra-runtime = {path = "../../runtime/selendra" }

[dev-dependencies]
wat = "1.0"
criterion = "0.3.0"
futures = "0.3.21"

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }

pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
pallet-im-online = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
pallet-treasury = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }

sp-application-crypto = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-externalities = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.23" }

selendra-node-test = { path = "../test" }
selendra-runtime-constants = { path = "../../runtime/selendra/constants" }

[features]
wasmtime = ["sc-executor/wasmtime"]
wasmi-errno = ["sc-executor/wasmi-errno"]
stress-test = []

[[bench]]
name = "bench"
harness = false
