[package]
name = "selendra-dispute-distribution"
version = "0.2.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
derive_more = "0.99.17"
thiserror = "1.0.31"
fatality = "0.0.6"
lru = "0.7.7"
parity-scale-codec = { version = "3.1.5", features = ["std"] }

sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }

selendra-primitives = { path = "../../../../primitives" }
selendra-erasure-coding = { path = "../../erasure-coding" }
selendra-node-subsystem = {path = "../../subsystem" }
selendra-node-network-protocol = { path = "../../network/protocol" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-node-primitives = { path = "../../primitives" }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
async-trait = "0.1.53"
futures-timer = "3.0.2"
assert_matches = "1.4.0"
lazy_static = "1.4.0"

sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26" }

node-subsystem-test-helpers = { path = "../../../../test-helper/subsystem" }
primitives-test-helpers = { path = "../../../../test-helper/primitive" }
