[package]
name = "selendra-node-core-provisioner"
version = "0.2.3"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
futures = "0.3.21"
futures-timer = "3.0.2"
rand = "0.8.5"
fatality = "0.0.6"
thiserror = "1.0.31"

selendra-primitives = { path = "../../../../primitives" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem = { path = "../../subsystem" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30" }
node-subsystem-test-helpers = { path = "../../../../tests/test-helpers/subsystem" }
test-helpers = { package = "primitives-test-helpers", path = "../../../../tests/test-helpers/primitive" }
