[package]
name = "selendra-statement-distribution"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
description = "Statement Distribution Subsystem"
edition = "2021"

[dependencies]
futures = "0.3.21"
thiserror = "1.0.31"
fatality = "0.0.6"
arrayvec = "0.5.2"
indexmap = "1.9.0"
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }

sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.27" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }

selendra-primitives = { path = "../../../../primitives" }
selendra-node-subsystem = {path = "../../subsystem" }
selendra-node-primitives = { path = "../../primitives" }
selendra-node-subsystem-util = { path = "../../subsystem-util" }
selendra-node-network-protocol = { path = "../../network/protocol" }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
assert_matches = "1.4.0"
futures-timer = "3.0.2"
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }

node-subsystem-test-helpers = { path = "../../../../tests/test-helpers/subsystem" }
primitives-test-helpers = { path = "../../../../tests/test-helpers/primitive" }
