[package]
name = "selendra-node-core-pvf"
version = "1.0.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[[bin]]
name = "puppet_worker"
path = "bin/puppet_worker.rs"

[dependencies]
always-assert = "0.1"
futures = "0.3.21"
futures-timer = "3.0.2"
libc = "0.2.139"
pin-project = "1.0.9"
rand = "0.8.5"
slotmap = "1.0"
tempfile = "3.3.0"
tokio = { version = "1.24.2", features = ["fs", "process"] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-wasm-interface = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-maybe-compressed-blob = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

gum = { package = "tracing-gum", path = "../../gum" }
selendra-parachain = { path = "../../../../parachain" }
selendra-core-primitives = { path = "../../../../primitives/core" }
selendra-node-core-pvf-common = { path = "common" }
selendra-node-core-pvf-execute-worker = { path = "execute-worker" }
selendra-node-core-pvf-prepare-worker = { path = "prepare-worker" }
selendra-node-metrics = { path = "../../metrics"}
selendra-node-primitives = { path = "../../primitives" }
selendra-primitives = { path = "../../../../primitives" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

[dev-dependencies]
assert_matches = "1.4.0"
hex-literal = "0.3.4"

adder = { package = "test-parachain-adder", path = "../../../../parachain/test-parachains/adder" }
halt = { package = "test-parachain-halt", path = "../../../../parachain/test-parachains/halt" }

[features]
ci-only-tests = []
